version: '3'

services:
  personal-tracker-app:
    container_name: tracker-app
    build:
      context: .
      dockerfile: AppDockerfile
    ports: 
     - '3000:3000'
    restart: unless-stopped
    links:
      - tracker-db
  tracker-db:
    container_name: tracker-db
    image: mongo
    volumes: 
      - ./data/db:/data/db
    ports:
      - '27018:27017'